/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_dd_diffserver_Diff */

#ifndef _Included_com_dd_diffserver_Diff
#define _Included_com_dd_diffserver_Diff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dd_diffserver_Diff
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dd_diffserver_Diff_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
